[versions]
minecraft = '1.19.2'

[libraries]
# https://lambdaurora.dev/tools/import_quilt.html
minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }
quilt_mappings = 'org.quiltmc:quilt-mappings:1.19.2+build.21'
quilt_loader = 'org.quiltmc:quilt-loader:0.17.4'
quilted_fabric_api = 'org.quiltmc.quilted-fabric-api:quilted-fabric-api:4.0.0-beta.16+0.64.0-1.19.2'

midnightlib = 'maven.modrinth:midnightlib:0.6.1'

mod_menu = 'com.terraformersmc:modmenu:4.0.6'

[bundles]
quilt = ['quilt_loader', 'quilted_fabric_api']

[plugins]
quilt_loom = 'org.quiltmc.loom:1.0.+'
quilt_licenser = 'org.quiltmc.gradle.licenser:1.+'
minotaur = 'com.modrinth.minotaur:2.+'
machete = 'io.github.p03w.machete:1.+'
